In [3]:
import pandas as pd
import numpy as np
import json as simplejson
from datetime import datetime, timedelta

# Exercise 1: Create a new column that contains only the zipcode.

In [45]:
data = []
with open ('yelp_academic_dataset_business.json') as f:
    for line in f:
        data.append(simplejson.loads(line))

df = pd.DataFrame(data[:5000])
df.head()

,attributes,business_id,categories,city,full_address,hours,latitude,longitude,name,neighborhoods,open,review_count,stars,state,type
0,"{'Good For': {'breakfast': False, 'lunch': Fal...",5UmKMjUEUNdYWqANhGckJw,"[Fast Food, Restaurants]",Dravosburg,"4734 Lebanon Church Rd\nDravosburg, PA 15034","{'Wednesday': {'open': '11:00', 'close': '21:0...",40.354327,-79.900706,Mr Hoagie,[],True,7,3.5,PA,business
1,"{'Price Range': 1, 'Accepts Credit Cards': Tru...",UsFtqoBl7naz8AVUBZMjQQ,[Nightlife],Dravosburg,"202 McClure St\nDravosburg, PA 15034",{},40.350553,-79.886814,Clancy's Pub,[],True,5,3.0,PA,business
2,{'Good for Kids': True},cE27W9VPgO88Qxe4ol6y_g,"[Active Life, Mini Golf, Golf]",Bethel Park,"1530 Hamilton Rd\nBethel Park, PA 15234",{},40.354115,-80.014660,Cool Springs Golf Center,[],False,5,2.5,PA,business
3,"{'Noise Level': 'average', 'Delivery': False, ...",mVHrayjG3uZ_RLHkLj-AMg,"[Bars, American (New), Nightlife, Lounges, Res...",Braddock,"414 Hawkins Ave\nBraddock, PA 15104","{'Wednesday': {'open': '10:00', 'close': '19:0...",40.408830,-79.866211,Emil's Lounge,[],True,26,4.5,PA,business
4,"{'Good for Kids': True, 'Parking': {'lot': Fal...",mYSpR_SLPgUVymYOvTQd_Q,"[Active Life, Golf]",Braddock,"1000 Clubhouse Dr\nBraddock, PA 15104","{'Wednesday': {'open': '11:00', 'close': '20:0...",40.403405,-79.855782,Grand View Golf Club,[],True,3,5.0,PA,business

In [46]:
# isolating zipcode from address check
df.full_address[0].split(' ')[-1]

'15034'

In [47]:
# lambda function using parameter 1 to apply to each row
df['zipcode'] = df.apply(lambda x: x['full_address'].split(' ')[-1], 1)

# Exercise 2: The table contains a column called 'categories' and each entry in this column is populated by a list. We are interested in those businesses that are restaurants. Create a new column 'restaurant_type' that contains a description of the restaurant based on the other elements of 'categories. That is, if we have '[Sushi Bars, Japanese, Restaurants]' in categories the 'restaurant_type will be '{'SushiBars': 1, 'Japanese': 1, 'Mexican': 0, ...}'

In [48]:
categories = {}

# separate all rows with restaurants and keep category, assign 0 initially
for index, row in df.iterrows():
    if 'Restaurants' in row['categories']:
        for el in row['categories']:
            if el != 'Restaurants':
                categories[el] = 0

In [49]:
categories

{'Active Life': 0,
 'American (New)': 0,
 'American (Traditional)': 0,
 'Antiques': 0,
 'Arcades': 0,
 'Arts & Entertainment': 0,
 'Asian Fusion': 0,
 'Automotive': 0,
 'Bagels': 0,
 'Bakeries': 0,
 'Barbeque': 0,
 'Bars': 0,
 'Bed & Breakfast': 0,
 'Beer, Wine & Spirits': 0,
 'Bowling': 0,
 'Breakfast & Brunch': 0,
 'Breweries': 0,
 'British': 0,
 'Buffets': 0,
 'Burgers': 0,
 'Cafes': 0,
 'Cafeteria': 0,
 'Cajun/Creole': 0,
 'Caribbean': 0,
 'Caterers': 0,
 'Cheese Shops': 0,
 'Cheesesteaks': 0,
 'Chicken Wings': 0,
 'Chinese': 0,
 'Cocktail Bars': 0,
 'Coffee & Tea': 0,
 'Comfort Food': 0,
 'Convenience Stores': 0,
 'Creperies': 0,
 'Cuban': 0,
 'Dance Clubs': 0,
 'Delis': 0,
 'Desserts': 0,
 'Diners': 0,
 'Dive Bars': 0,
 'Donuts': 0,
 'Ethiopian': 0,
 'Ethnic Food': 0,
 'Event Planning & Services': 0,
 'Fast Food': 0,
 'Fish & Chips': 0,
 'Fondue': 0,
 'Food': 0,
 'French': 0,
 'Fruits & Veggies': 0,
 'Gas & Service Stations': 0,
 'Gastropubs': 0,
 'German': 0,
 'Gluten-Free': 0,
 'Greek': 0,
 'Grocery': 0,
 'Hawaiian': 0,
 'Health Markets': 0,
 'Hookah Bars': 0,
 'Hot Dogs': 0,
 'Hotels': 0,
 'Hotels & Travel': 0,
 'Ice Cream & Frozen Yogurt': 0,
 'Indian': 0,
 'Irish': 0,
 'Italian': 0,
 'Japanese': 0,
 'Jazz & Blues': 0,
 'Karaoke': 0,
 'Korean': 0,
 'Kosher': 0,
 'Latin American': 0,
 'Lebanese': 0,
 'Lounges': 0,
 'Meat Shops': 0,
 'Mediterranean': 0,
 'Mexican': 0,
 'Middle Eastern': 0,
 'Music Venues': 0,
 'New Mexican Cuisine': 0,
 'Nightlife': 0,
 'Noodles': 0,
 'Pakistani': 0,
 'Party & Event Planning': 0,
 'Persian/Iranian': 0,
 'Peruvian': 0,
 'Pizza': 0,
 'Polish': 0,
 'Pool Halls': 0,
 'Portuguese': 0,
 'Pubs': 0,
 'Ramen': 0,
 'Russian': 0,
 'Salad': 0,
 'Salvadoran': 0,
 'Sandwiches': 0,
 'Seafood': 0,
 'Shopping': 0,
 'Soul Food': 0,
 'Soup': 0,
 'Southern': 0,
 'Spanish': 0,
 'Specialty Food': 0,
 'Sports Bars': 0,
 'Steakhouses': 0,
 'Sushi Bars': 0,
 'Taiwanese': 0,
 'Tapas Bars': 0,
 'Tapas/Small Plates': 0,
 'Tea Rooms': 0,
 'Teppanyaki': 0,
 'Tex-Mex': 0,
 'Thai': 0,
 'Vegan': 0,
 'Vegetarian': 0,
 'Venues & Event Spaces': 0,
 'Vietnamese': 0,
 'Wine Bars': 0}

In [50]:
def category(row):
    d = dict(categories)
    if 'Restaurants' in row['categories']:
        for el in row['categories']:
            if el in d.keys():
                d[el] = 1
            else:
                d[el] = 0
    else:
        d = 'Remove'
        
    return d

In [51]:
df['restaurant_type'] = df.apply(lambda x: category(x) , 1)

In [52]:
df.head()

,attributes,business_id,categories,city,full_address,hours,latitude,longitude,name,neighborhoods,open,review_count,stars,state,type,zipcode,restaurant_type
0,"{'Good For': {'breakfast': False, 'lunch': Fal...",5UmKMjUEUNdYWqANhGckJw,"[Fast Food, Restaurants]",Dravosburg,"4734 Lebanon Church Rd\nDravosburg, PA 15034","{'Wednesday': {'open': '11:00', 'close': '21:0...",40.354327,-79.900706,Mr Hoagie,[],True,7,3.5,PA,business,15034,"{'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':..."
1,"{'Price Range': 1, 'Accepts Credit Cards': Tru...",UsFtqoBl7naz8AVUBZMjQQ,[Nightlife],Dravosburg,"202 McClure St\nDravosburg, PA 15034",{},40.350553,-79.886814,Clancy's Pub,[],True,5,3.0,PA,business,15034,Remove
2,{'Good for Kids': True},cE27W9VPgO88Qxe4ol6y_g,"[Active Life, Mini Golf, Golf]",Bethel Park,"1530 Hamilton Rd\nBethel Park, PA 15234",{},40.354115,-80.014660,Cool Springs Golf Center,[],False,5,2.5,PA,business,15234,Remove
3,"{'Noise Level': 'average', 'Delivery': False, ...",mVHrayjG3uZ_RLHkLj-AMg,"[Bars, American (New), Nightlife, Lounges, Res...",Braddock,"414 Hawkins Ave\nBraddock, PA 15104","{'Wednesday': {'open': '10:00', 'close': '19:0...",40.408830,-79.866211,Emil's Lounge,[],True,26,4.5,PA,business,15104,"{'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':..."
4,"{'Good for Kids': True, 'Parking': {'lot': Fal...",mYSpR_SLPgUVymYOvTQd_Q,"[Active Life, Golf]",Braddock,"1000 Clubhouse Dr\nBraddock, PA 15104","{'Wednesday': {'open': '11:00', 'close': '20:0...",40.403405,-79.855782,Grand View Golf Club,[],True,3,5.0,PA,business,15104,Remove

# Exercise 3: Lets clean the 'attributes' column. The entries in this column are dictionaries. We need to do two things:

1) Turn all the True or False values in the dictionary to 1 and 0.

2) There are some entries within dictionaries that are dictionaries themselves, lets turn the whole entry into just one dictionary, for example if we have

'{'Accepts Credit Cards': True, 'Alcohol': 'none','Ambience': {'casual': False,'classy': False}}'

then turn it into

'{'Accepts Credit Cards':1, 'Alcohol': 0, 'Ambience_casual': 0, 'Ambience_classy': 0}'.

There might be other entries like {'Price Range': 1} where the values are numerical so we might want to change that into {'Price_Range_1': 1}.

In [53]:
df.attributes[:10]

0    {'Good For': {'breakfast': False, 'lunch': Fal...
1    {'Price Range': 1, 'Accepts Credit Cards': Tru...
2                              {'Good for Kids': True}
3    {'Noise Level': 'average', 'Delivery': False, ...
4    {'Good for Kids': True, 'Parking': {'lot': Fal...
5    {'Noise Level': 'loud', 'Delivery': False, 'Ca...
6                       {'Accepts Credit Cards': True}
7                              {'Good for Kids': True}
8                                                   {}
9                                                   {}
Name: attributes, dtype: object

In [54]:
def flatten(row):
    d = row['attributes']
    d1 = {}
    
    # iterate over the keys
    for el in d.keys():
        
        # if value boolean 1 and 0
        if type(d[el]) == bool:
            d1[el] = int(d[el])
        
        # join strings
        elif type(d[el]) == str:
            label = '{}_{}'.format(el, d[el])
            d1[label] = 1
        
        # join integers
        elif type(d[el]) == int:
            label = '{}_{}'.format(el, d[el])
            d1[label] = 1
        
        # nested dictionaries
        elif type(d[el]) == dict:
            for elem in d[el].keys():
                label = '{}_{}'.format(el, elem)
                d1[label] = int(d[el][elem])
        
        # edge case check
        else:
            print(el, d[el])

    return d1

In [55]:
df['attributes_cleaned'] = df.apply(lambda x: flatten(x), 1)

In [56]:
df['attributes_cleaned']

0       {'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...
1       {'Accepts Credit Cards': 1, 'Happy Hour': 1, '...
2                                    {'Good for Kids': 1}
3       {'Delivery': 0, 'Ambience_touristy': 0, 'Coat ...
4       {'Parking_valet': 0, 'Parking_validated': 0, '...
5       {'Delivery': 0, 'Ambience_touristy': 0, 'Coat ...
6                             {'Accepts Credit Cards': 1}
7                                    {'Good for Kids': 1}
8                                                      {}
9                                                      {}
10                                      {'Wi-Fi_free': 1}
11                                                     {}
12      {'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...
13      {'Parking_valet': 0, 'Take-out': 1, 'Parking_v...
14                                                     {}
15                            {'Accepts Credit Cards': 1}
16                                                     {}
17      {'Delivery': 0, 'Parking_valet': 0, 'Coat Chec...
18      {'Delivery': 0, 'Ambience_touristy': 0, 'Alcoh...
19      {'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...
20      {'Wi-Fi_free': 1, 'Accepts Credit Cards': 1, '...
21      {'Parking_valet': 0, 'Delivery': 0, 'Good For_...
22                                                     {}
23                            {'Accepts Credit Cards': 0}
24      {'Delivery': 0, 'Parking_valet': 0, 'Alcohol_n...
25                             {'By Appointment Only': 1}
26      {'Delivery': 1, 'Parking_valet': 0, 'Alcohol_n...
27                                                     {}
28      {'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...
29      {'Parking_valet': 0, 'Parking_validated': 0, '...
                              ...
4970                                                   {}
4971    {'Parking_valet': 0, 'Parking_validated': 0, '...
4972                          {'Accepts Credit Cards': 1}
4973                          {'Accepts Credit Cards': 1}
4974    {'Parking_valet': 0, 'Delivery': 0, 'Good For_...
4975    {'Parking_valet': 0, 'Delivery': 0, 'Good For_...
4976    {'Delivery': 0, 'Ambience_touristy': 0, 'Alcoh...
4977    {'Parking_valet': 0, 'Parking_validated': 0, '...
4978    {'Parking_valet': 0, 'By Appointment Only': 0,...
4979    {'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...
4980    {'Wi-Fi_free': 1, 'Take-out': 1, 'Parking_vali...
4981                                 {'Good for Kids': 1}
4982                                 {'Good for Kids': 1}
4983                                 {'Good for Kids': 1}
4984    {'Parking_valet': 0, 'Parking_validated': 0, '...
4985    {'Delivery': 0, 'Parking_valet': 0, 'Good For_...
4986    {'Wheelchair Accessible': 1, 'Dogs Allowed': 1...
4987                           {'By Appointment Only': 0}
4988    {'Parking_valet': 0, 'Take-out': 1, 'Parking_v...
4989    {'Delivery': 0, 'Parking_valet': 0, 'Alcohol_n...
4990    {'Parking_valet': 0, 'Take-out': 0, 'Parking_v...
4991    {'Delivery': 1, 'Ambience_touristy': 0, 'Good ...
4992                                                   {}
4993    {'Delivery': 0, 'Ambience_touristy': 0, 'Good ...
4994    {'Parking_valet': 0, 'Parking_validated': 0, '...
4995    {'Wheelchair Accessible': 1, 'Accepts Credit C...
4996    {'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...
4997    {'Parking_valet': 0, 'Parking_validated': 0, '...
4998    {'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...
4999    {'Wi-Fi_free': 1, 'Accepts Credit Cards': 1, '...
Name: attributes_cleaned, dtype: object

# 4. Create a new column for every day of the week and fill it with the amount of hours the business is open that day.

In [57]:
df.hours[:5]

0    {'Wednesday': {'open': '11:00', 'close': '21:0...
1                                                   {}
2                                                   {}
3    {'Wednesday': {'open': '10:00', 'close': '19:0...
4    {'Wednesday': {'open': '11:00', 'close': '20:0...
Name: hours, dtype: object

In [58]:
days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday','Saturday']

In [59]:
FMT = '%H:%M'

def time(row, date):
    try:
        closing = datetime.strptime(row['hours'][day]['close'], FMT)
        opening = datetime.strptime(row['hours'][day]['open'], FMT)

        time = closing - opening
        # check for different days

        if time <= timedelta(days=0):
            time +- timedelta(days=1)

    except:
            time = timedelta(days=0)
    
    return time

In [60]:
for day in days:
    df[day] = df.apply(lambda x: time(x, day), 1)

In [61]:
df.head()

,attributes,business_id,categories,city,full_address,hours,latitude,longitude,name,neighborhoods,...,zipcode,restaurant_type,attributes_cleaned,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday
0,"{'Good For': {'breakfast': False, 'lunch': Fal...",5UmKMjUEUNdYWqANhGckJw,"[Fast Food, Restaurants]",Dravosburg,"4734 Lebanon Church Rd\nDravosburg, PA 15034","{'Wednesday': {'open': '11:00', 'close': '21:0...",40.354327,-79.900706,Mr Hoagie,[],...,15034,"{'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':...","{'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...",00:00:00,10:00:00,10:00:00,10:00:00,10:00:00,10:00:00,00:00:00
1,"{'Price Range': 1, 'Accepts Credit Cards': Tru...",UsFtqoBl7naz8AVUBZMjQQ,[Nightlife],Dravosburg,"202 McClure St\nDravosburg, PA 15034",{},40.350553,-79.886814,Clancy's Pub,[],...,15034,Remove,"{'Accepts Credit Cards': 1, 'Happy Hour': 1, '...",00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00
2,{'Good for Kids': True},cE27W9VPgO88Qxe4ol6y_g,"[Active Life, Mini Golf, Golf]",Bethel Park,"1530 Hamilton Rd\nBethel Park, PA 15234",{},40.354115,-80.014660,Cool Springs Golf Center,[],...,15234,Remove,{'Good for Kids': 1},00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00
3,"{'Noise Level': 'average', 'Delivery': False, ...",mVHrayjG3uZ_RLHkLj-AMg,"[Bars, American (New), Nightlife, Lounges, Res...",Braddock,"414 Hawkins Ave\nBraddock, PA 15104","{'Wednesday': {'open': '10:00', 'close': '19:0...",40.408830,-79.866211,Emil's Lounge,[],...,15104,"{'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':...","{'Delivery': 0, 'Ambience_touristy': 0, 'Coat ...",00:00:00,00:00:00,09:00:00,09:00:00,09:00:00,10:00:00,06:00:00
4,"{'Good for Kids': True, 'Parking': {'lot': Fal...",mYSpR_SLPgUVymYOvTQd_Q,"[Active Life, Golf]",Braddock,"1000 Clubhouse Dr\nBraddock, PA 15104","{'Wednesday': {'open': '11:00', 'close': '20:0...",40.403405,-79.855782,Grand View Golf Club,[],...,15104,Remove,"{'Parking_valet': 0, 'Parking_validated': 0, '...",05:00:00,00:00:00,00:00:00,09:00:00,09:00:00,09:00:00,09:00:00

# 5. Create a table with the average star review for a business from the review table.

In [33]:
data_review = []

with open('yelp_academic_dataset_review.json') as f:
    for line in f:
        data_review.append(simplejson.loads(line))
        
df_review = pd.DataFrame(data_review[:5000])
df_review.head()

,business_id,date,review_id,stars,text,type,user_id,votes
0,5UmKMjUEUNdYWqANhGckJw,2012-08-01,Ya85v4eqdd6k9Od8HbQjyA,4,"Mr Hoagie is an institution. Walking in, it do...",review,PUFPaY9KxDAcGqfsorJp3Q,"{'useful': 0, 'cool': 0, 'funny': 0}"
1,5UmKMjUEUNdYWqANhGckJw,2014-02-13,KPvLNJ21_4wbYNctrOwWdQ,5,Excellent food. Superb customer service. I mis...,review,Iu6AxdBYGR4A0wspR9BYHA,"{'useful': 0, 'cool': 0, 'funny': 0}"
2,5UmKMjUEUNdYWqANhGckJw,2015-10-31,fFSoGV46Yxuwbr3fHNuZig,5,Yes this place is a little out dated and not o...,review,auESFwWvW42h6alXgFxAXQ,"{'useful': 1, 'cool': 0, 'funny': 1}"
3,5UmKMjUEUNdYWqANhGckJw,2015-12-26,pVMIt0a_QsKtuDfWVfSk2A,3,PROS: Italian hoagie was delicious. Friendly ...,review,qiczib2fO_1VBG8IoCGvVg,"{'useful': 0, 'cool': 0, 'funny': 0}"
4,5UmKMjUEUNdYWqANhGckJw,2016-04-08,AEyiQ_Y44isJmNbMTyoMKQ,2,First the only reason this place could possibl...,review,qEE5EvV-f-s7yHC0Z4ydJQ,"{'useful': 1, 'cool': 0, 'funny': 0}"

In [34]:
average_rating = df_review.groupby('business_id')['stars'].mean().reset_index()

In [35]:
average_rating.columns = ['business_id', 'star_avg']

In [36]:
average_rating.head()

              business_id  star_avg
0  -Gfj1gA0Ir07zToO-4fBpw  4.772727
1  -iVcmhjfq79QoTWzrb6pKg  4.263889
2  -nO_qj9eP-os3baYyh8eNA  4.200000
3  -raHHPz6kBnQgBH-oCuDFA  2.166667
4  -taSf0shFSUKy9iCXnySsA  2.400000

In [37]:
df_review = df_review.merge(average_rating, how='left', on='business_id')
df_review.head()

,business_id,date,review_id,stars,text,type,user_id,votes,star_avg
0,5UmKMjUEUNdYWqANhGckJw,2012-08-01,Ya85v4eqdd6k9Od8HbQjyA,4,"Mr Hoagie is an institution. Walking in, it do...",review,PUFPaY9KxDAcGqfsorJp3Q,"{'useful': 0, 'cool': 0, 'funny': 0}",3.428571
1,5UmKMjUEUNdYWqANhGckJw,2014-02-13,KPvLNJ21_4wbYNctrOwWdQ,5,Excellent food. Superb customer service. I mis...,review,Iu6AxdBYGR4A0wspR9BYHA,"{'useful': 0, 'cool': 0, 'funny': 0}",3.428571
2,5UmKMjUEUNdYWqANhGckJw,2015-10-31,fFSoGV46Yxuwbr3fHNuZig,5,Yes this place is a little out dated and not o...,review,auESFwWvW42h6alXgFxAXQ,"{'useful': 1, 'cool': 0, 'funny': 1}",3.428571
3,5UmKMjUEUNdYWqANhGckJw,2015-12-26,pVMIt0a_QsKtuDfWVfSk2A,3,PROS: Italian hoagie was delicious. Friendly ...,review,qiczib2fO_1VBG8IoCGvVg,"{'useful': 0, 'cool': 0, 'funny': 0}",3.428571
4,5UmKMjUEUNdYWqANhGckJw,2016-04-08,AEyiQ_Y44isJmNbMTyoMKQ,2,First the only reason this place could possibl...,review,qEE5EvV-f-s7yHC0Z4ydJQ,"{'useful': 1, 'cool': 0, 'funny': 0}",3.428571

# 6. Create a new table that only contains restaurants with the following schema:
Business_Name | Restaurant_type | Friday hours | Saturday hours | Attributes | Zipcode | Average Rating

In [64]:
df_final = df_review.merge(df, how='left', on='business_id')
df_final['restaurant_type'].head()

0    {'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':...
1    {'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':...
2    {'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':...
3    {'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':...
4    {'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':...
Name: restaurant_type, dtype: object

In [40]:
df_final = df_review.merge(df, how='left', on='business_id')
df_final.head()

,business_id,date,review_id,stars_x,text,type_x,user_id,votes,star_avg,attributes,...,type_y,zipcode,attributes_cleaned,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday
0,5UmKMjUEUNdYWqANhGckJw,2012-08-01,Ya85v4eqdd6k9Od8HbQjyA,4,"Mr Hoagie is an institution. Walking in, it do...",review,PUFPaY9KxDAcGqfsorJp3Q,"{'useful': 0, 'cool': 0, 'funny': 0}",3.428571,"{'Good For': {'breakfast': False, 'lunch': Fal...",...,business,15034,"{'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...",0 days,10:00:00,10:00:00,10:00:00,10:00:00,10:00:00,0 days
1,5UmKMjUEUNdYWqANhGckJw,2014-02-13,KPvLNJ21_4wbYNctrOwWdQ,5,Excellent food. Superb customer service. I mis...,review,Iu6AxdBYGR4A0wspR9BYHA,"{'useful': 0, 'cool': 0, 'funny': 0}",3.428571,"{'Good For': {'breakfast': False, 'lunch': Fal...",...,business,15034,"{'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...",0 days,10:00:00,10:00:00,10:00:00,10:00:00,10:00:00,0 days
2,5UmKMjUEUNdYWqANhGckJw,2015-10-31,fFSoGV46Yxuwbr3fHNuZig,5,Yes this place is a little out dated and not o...,review,auESFwWvW42h6alXgFxAXQ,"{'useful': 1, 'cool': 0, 'funny': 1}",3.428571,"{'Good For': {'breakfast': False, 'lunch': Fal...",...,business,15034,"{'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...",0 days,10:00:00,10:00:00,10:00:00,10:00:00,10:00:00,0 days
3,5UmKMjUEUNdYWqANhGckJw,2015-12-26,pVMIt0a_QsKtuDfWVfSk2A,3,PROS: Italian hoagie was delicious. Friendly ...,review,qiczib2fO_1VBG8IoCGvVg,"{'useful': 0, 'cool': 0, 'funny': 0}",3.428571,"{'Good For': {'breakfast': False, 'lunch': Fal...",...,business,15034,"{'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...",0 days,10:00:00,10:00:00,10:00:00,10:00:00,10:00:00,0 days
4,5UmKMjUEUNdYWqANhGckJw,2016-04-08,AEyiQ_Y44isJmNbMTyoMKQ,2,First the only reason this place could possibl...,review,qEE5EvV-f-s7yHC0Z4ydJQ,"{'useful': 1, 'cool': 0, 'funny': 0}",3.428571,"{'Good For': {'breakfast': False, 'lunch': Fal...",...,business,15034,"{'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...",0 days,10:00:00,10:00:00,10:00:00,10:00:00,10:00:00,0 days

In [65]:
df_final = df_final[df_final['restaurant_type'] != 'Remove']

In [66]:
df_final = df_final[['name', 'restaurant_type', 'Friday', 'Saturday', 'attributes_cleaned', 'zipcode', 'star_avg']]

In [67]:
df_final.head()

,name,restaurant_type,Friday,Saturday,attributes_cleaned,zipcode,star_avg
0,Mr Hoagie,"{'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':...",10:00:00,0 days,"{'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...",15034,3.428571
1,Mr Hoagie,"{'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':...",10:00:00,0 days,"{'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...",15034,3.428571
2,Mr Hoagie,"{'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':...",10:00:00,0 days,"{'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...",15034,3.428571
3,Mr Hoagie,"{'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':...",10:00:00,0 days,"{'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...",15034,3.428571
4,Mr Hoagie,"{'Taiwanese': 0, 'Cajun/Creole': 0, 'Seafood':...",10:00:00,0 days,"{'Parking_valet': 0, 'Delivery': 0, 'Alcohol_n...",15034,3.428571